### ISSUE TITLE
Log implicit returns to native console

### ISSUE THREAD

**Issue by dwelle** [IceCreamYou/Chrome-BigConsole#13] opened 2016-09-28 11:43 UTC
Log implicit returns to native console, and possibly allow to hide BigConsole output, since currently due to how the BigConsole displays (large) objects, it's very cluttered.

Currently, I work around it by using `console.log()` and resizing windows like this:

![image](https://cloud.githubusercontent.com/assets/5153846/18912192/778958ee-8581-11e6-9aec-c2542f5f6a61.png)

but it's not very convenient.

**Comment by IceCreamYou** [comment] 2016-09-28 17:22
I think this is a duplicate of #7 - ideally the BigConsole console output would be improved rather than using other workarounds.

**Closed as completed by IceCreamYou** 2016-09-28 17:23 UTC
